In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets

iris_data = datasets.load_iris()
features = iris_data.data
targets = iris_data.target

print(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
print(targets)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
# criterion='entropy'

model = DecisionTreeClassifier(criterion='entropy')
model.fit(features,targets)
y_pred = model.predict([[6.4, 3.2, 5.3, 2.3]])
print(y_pred)

if y_pred == [2]:
print("Success")

[2]
Success


In [8]:
#Accuracy Testing

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
feature_train, feature_test, target_train, traget_test = train_test_split(features, targets, test_size=0.2)
model = DecisionTreeClassifier(criterion='entropy')
predicted = cross_validate(model, features, targets, cv=10)
print(np.mean(predicted['test_score']))

0.9533333333333334


In [12]:
# criterion='gini'

model = DecisionTreeClassifier(criterion='gini')
model.fit(features,targets)
y_pred = model.predict([[6.4, 3.2, 5.3, 2.3]])
print(y_pred)

if y_pred == [2]:
  print("Success")

[2]
Success


In [10]:
#Accuracy Testing

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
feature_train, feature_test, target_train, traget_test = train_test_split(features, targets, test_size=0.2)
model = DecisionTreeClassifier(criterion='gini')
predicted = cross_validate(model, features, targets, cv=10)
print(np.mean(predicted['test_score']))

0.96


In [14]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np


x = []
for i in range(1001):
  x.append([i])

y = []
for i in range(1001):
  val = 2*i + 3
  y.append(val)


model = DecisionTreeClassifier(criterion='gini')
model.fit(x,y)
model.predict([[345]])

array([693])

In [15]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np


x = []
for i in range(101):
  x.append([i])

y = []
for i in range(101):
  val = 2*i + 3
  y.append(val)


model = DecisionTreeClassifier(criterion='gini')
model.fit(x,y)
model.predict([[345]])

array([203])